package uz.com.enums;

public interface Permissions {

    /**
     * USER
     */
    String USER = "USER";
    String USER_READ = "USER_READ";
    String USER_CREATE = "USER_CREATE";
    String USER_UPDATE = "USER_UPDATE";
    String USER_DELETE = "USER_DELETE";
    String USER_ATTACH_ROLE = "USER_ATTACH_ROLE";
    String USER_CHANGE_PASSWORD= "USER_CHANGE_PASSWORD";

    /**
     * ROLE
     */
    String ROLE = "ROLE";
    String ROLE_READ = "ROLE_READ";
    String ROLE_CREATE = "ROLE_CREATE";
    String ROLE_UPDATE = "ROLE_UPDATE";
    String ROLE_DELETE = "ROLE_DELETE";
    String ROLE_ATTACH_PERMISSION = "ROLE_ATTACH_PERMISSION";

    /**
     * PERMISSION
     */
    String PERMISSION = "PERMISSION";
    String PERMISSION_READ = "PERMISSION_READ";
    String PERMISSION_CREATE = "PERMISSION_CREATE";
    String PERMISSION_UPDATE = "PERMISSION_UPDATE";
    String PERMISSION_DELETE = "PERMISSION_DELETE";

    /**
     * SETTINGS TYPE
     */
    String SETTINGS_TYPE = "SETTING_TYPE";
    String SETTINGS_TYPE_READ = "SETTINGS_TYPE_READ";
    String SETTINGS_TYPE_CREATE = "SETTINGS_TYPE_CREATE";
    String SETTINGS_TYPE_UPDATE = "SETTINGS_TYPE_UPDATE";
    String SETTINGS_TYPE_DELETE = "SETTINGS_TYPE_DELETE";

    /**
     * BUSINESS_DIRECTION
     */
    String BUSINESS_DIRECTION = "BUSINESS_DIRECTION";
    String BUSINESS_DIRECTION_READ = "BUSINESS_DIRECTION_READ";
    String BUSINESS_DIRECTION_CREATE = "BUSINESS_DIRECTION_CREATE";
    String BUSINESS_DIRECTION_UPDATE = "BUSINESS_DIRECTION_UPDATE";
    String BUSINESS_DIRECTION_DELETE = "BUSINESS_DIRECTION_DELETE";

    /**
     * ORGANIZATION
     */
    String ORGANIZATION = "ORGANIZATION";
    String ORGANIZATION_READ = "ORGANIZATION_READ";
    String ORGANIZATION_CREATE = "ORGANIZATION_CREATE";
    String ORGANIZATION_UPDATE = "ORGANIZATION_UPDATE";
    String ORGANIZATION_DELETE = "ORGANIZATION_DELETE";

    /**
     * ORGANIZATION_ADDRESS
     */
    String ORGANIZATION_ADDRESS = "ORGANIZATION_ADDRESS";
    String ORGANIZATION_ADDRESS_READ = "ORGANIZATION_ADDRESS_READ";
    String ORGANIZATION_ADDRESS_CREATE = "ORGANIZATION_ADDRESS_CREATE";
    String ORGANIZATION_ADDRESS_UPDATE = "ORGANIZATION_ADDRESS_UPDATE";
    String ORGANIZATION_ADDRESS_DELETE = "ORGANIZATION_ADDRESS_DELETE";

    /**
     * ORGANIZATION_CONTACT
     */
    String ORGANIZATION_CONTACT = "ORGANIZATION_CONTACT";
    String ORGANIZATION_CONTACT_READ = "ORGANIZATION_CONTACT_READ";
    String ORGANIZATION_CONTACT_CREATE = "ORGANIZATION_CONTACT_CREATE";
    String ORGANIZATION_CONTACT_UPDATE = "ORGANIZATION_ADDRESS_UPDATE";
    String ORGANIZATION_CONTACT_DELETE = "ORGANIZATION_CONTACT_DELETE";

    /**
     * ORGANIZATION_MFO
     */
    String ORGANIZATION_MFO = "ORGANIZATION_MFO";
    String ORGANIZATION_MFO_READ = "ORGANIZATION_MFO_READ";
    String ORGANIZATION_MFO_CREATE = "ORGANIZATION_MFO_CREATE";
    String ORGANIZATION_MFO_UPDATE = "ORGANIZATION_MFO_UPDATE";
    String ORGANIZATION_MFO_DELETE = "ORGANIZATION_MFO_DELETE";
}
